# Lynx theme for Hugo

name = "lynx"
license = "MIT"
licenselink = "https://github.com/jpanther/lynx/blob/master/LICENSE"
description = "A links page theme for Hugo built with Tailwind CSS."

homepage = ""
demosite = ""

tags = ["minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["dark mode", "emoji"]

[author]
  name = "gomediakc"
  homepage = "https://gomediakc.com/"
