theme = "lynx"
title = "gomediakc"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "gomediakc"
  headline = "gomediakc"
  image = "https://app.gomediakc.com/asset-get/A0000fZdFYP8JpZA/GOMedia-Logo-Redesign-1-50x50-ICO.png"
  links = [
    { link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
    { link = { href = "styles/", text = "All the link styles", target = "_self" } },
    { github = "https://github.com/jpanther/lynx" },
    { x = "https://x.com/jpanther" },
    { font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
