theme = "lynx"
title = "gomediakc1"

enableEmoji = true
disableKinds = ["", ""]

[params.author]
  name = "gomediakc2"
  headline = "gomediakc3"
  image = "/GOMedia_Logo_Redesign_1_180x180_ICO.png""
  links = [
    { link = { href = "https://gomediakc.com", text = "View the readme", icon = "github" } },
    { link = { href = "styles/", text = "All the link styles", target = "_self" } },
    { github = "https://github.com/jpanther/lynx" },
    { x = "https://x.com/jpanther" },
    { font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
  ]

[markup.highlight]
  noClasses = true

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
